pfitzpaddy/ngm-reportHub

- app/promo/index.html
> Update promo page metrics text.

- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
fixes coordinates to be nulls, so that later could be filled with values from admin3 or admin2.
> fix: targetlocation facility coordinates.

- app/scripts/modules/cluster/services/ngmClusterHelper.js
> Update: + health facility type & beneficiaries.

- app/scripts/modules/cluster/dashboards/dashboard.admin.js
- app/scripts/modules/cluster/dashboards/dashboard.cluster.js
updates admin and 4w dashboards for cvwg cluster to have mpc in file downloads in place of cvwg
a temporary solution, maybe global update of cvwg cluster_id  is needed.
https://github.com/pfitzpaddy/ngm-reportDesk/issues/19
> update-temp: cvwg-to-mpc file downloads filename

- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
by flattening array and not using cluster_id for filtering, only strategic_objective_id
> bugfix: set strategic objective not using cluster for filtering

- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
- app/scripts/modules/cluster/views/forms/details/contact-details.html
- app/scripts/modules/cluster/views/forms/details/form.html
rabased follow up of https://github.com/pfitzpaddy/ngm-reportHub/pull/17
\+ updated card location and name
> Feature contact details experimental rebased

- app/scripts/modules/cluster/dashboards/dashboard.admin.js
- app/scripts/modules/cluster/reports/controllers/cluster.project.details.js
- app/scripts/modules/cluster/reports/controllers/cluster.project.projects.js
adds csv downloads in project details, project list, admin
> feature: add project export buttons

- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
- app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html
- app/scripts/modules/cluster/views/forms/details/target-locations/locations.html
> amend: index bug on cancel, scroll to benef

- app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js
- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
- app/scripts/widgets/ngm-list/template/report.html
+ last month first in list list (Dec, Nov, Oct) for convinient nav, delivery_type_id  (population) validation mandatory
> enhance: mreport: index bug: af population validation

- app/scripts/modules/cluster/reports/forms/cluster.organization.form.stock.js
- app/scripts/modules/cluster/views/forms/stock/form.html
- app/scripts/modules/cluster/views/forms/stock/locations.html
- app/scripts/modules/cluster/views/forms/stock/stocks.html
- app/scripts/widgets/ngm-list/template/report.html
- app/scripts/widgets/ngm-list/template/stock.html
+ stock reports last month first list, form message if not validated (check if needed)
validation as in monthly activity report,
> enhance: stock reporting: validation: cancel

- app/scripts/modules/cluster/reports/forms/cluster.organization.form.stock.js
- app/scripts/modules/cluster/views/forms/stock/form.html
- app/scripts/modules/cluster/views/forms/stock/locations.html
- app/scripts/modules/cluster/views/forms/stock/stocks.html
- app/scripts/widgets/ngm-list/template/report.html
- app/scripts/widgets/ngm-list/template/stock.html
in stock reporting
"operational projects stocks vs prepositioned stocks.
First is meant for the normal planned response, another is for emergencies, e.g. earthquakes."
> Feature stock purpose

- app/scripts/modules/cluster/reports/forms/cluster.organization.form.stock.js
- app/scripts/modules/cluster/services/ngmClusterHelper.js
- app/scripts/modules/cluster/views/forms/stock/form.html
- app/scripts/modules/cluster/views/forms/stock/locations.html
- app/scripts/modules/cluster/views/forms/stock/stocks.html
- app/scripts/widgets/ngm-list/template/report.html
- app/scripts/widgets/ngm-list/template/stock.html
copies rows from the previos report,
adds to existing, optionally can overwrite
> Feature cp prev report

- app/scripts/modules/cluster/dashboards/dashboard.admin.js
- app/scripts/modules/cluster/reports/controllers/cluster.organization.stock.js
- app/scripts/modules/cluster/reports/controllers/cluster.project.financials.js
adds export from project finance and admin dash
> feature: project/s csv financial export

- app/scripts/modules/cluster/services/ngmClusterHelper.js
deleted createdAt and updatedAt props to fix overwrite, note that that works only for createdAt, updatedAt will still be updated as we set entire report data.
> amend: report createdAt props not overwritten

- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
- app/scripts/modules/cluster/services/ngmClusterHelper.js
- app/scripts/modules/cluster/views/forms/details/strategic-objectives.html
revised afg SO for health, wash, fsac, mpc other pending, 
filtering by year, if project started last year will show also last year
> update: startegic objectives 2018 func

- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
- app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js
- app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html
also unblock edit button for target benef if activity missing
> amend: on activity obsolete on no data propmt to change

- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
- app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js
updates fatp treatment fields to have dash for other activities
> update: fatp change text for other activities

- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
- app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js
fixes issues with obsolete sub/activities like next in project def, and reports
> fix: if obsolete sub/activity

- app/scripts/app/controllers/admin/controller.authentication.js
- app/scripts/modules/cluster/dashboards/dashboard.cluster.js
just minor 'cvwg': { cluster: 'Cash ' } to  'cvwg': { cluster: 'MPC' }
> update: minor update cash to mpc

- app/scripts/modules/cluster/dashboards/dashboard.cluster.js
> update: training participants download button

- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
- app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js
- app/scripts/modules/cluster/services/ngmClusterHelper.js
- app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html
- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
> update: vactination_tt men/women show

- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
- app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js
- app/scripts/modules/cluster/services/ngmClusterHelper.js
- app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html
- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
updates for esnfi/protection new activities
> update: 2018 esnfi/protection

- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
- app/scripts/modules/cluster/services/ngmClusterHelper.js
if leaving not selected facility_type, it is copying previous entry, 
fix nulles the fields on add location
> fix: not copy facility_type_id /name

- app/scripts/modules/cluster/dashboards/dashboard.cluster.js
no download in 4w training_participants csv for AF
> update: no training download for AF

- app/scripts/modules/cluster/dashboards/dashboard.admin.js
- app/scripts/modules/cluster/dashboards/dashboard.cluster.js
request no EMRO/AFRO for organization view![2018-03-25_21-39-37](https://user-images.githubusercontent.com/29349472/37877898-706ff81e-3076-11e8-9b36-4889ea28d07f.gif)
> update: sub/title do not contain Rname on &lte contry level

- app/scripts/modules/cluster/views/forms/details/target-locations/locations.html
after applying patch setting admin1 row property _inactive:true_ will disable it from selection
> workaround: show old admin on its update

- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
- app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js
- app/scripts/modules/cluster/services/ngmClusterHelper.js
- app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html
- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
- app/scripts/modules/cluster/views/forms/report/locations.html
esnfi updates for updated activities reporting
> Update esnfi af

- app/scripts/modules/country/afghanistan/nutrition/app.js
- app/scripts/modules/country/afghanistan/nutrition/dashboards/dashboard.admin.nutrition.weekly.js
- app/scripts/modules/country/afghanistan/nutrition/dashboards/dashboard.nutrition.weekly.js
- app/scripts/modules/country/afghanistan/nutrition/services/ngmNutritionHelper.js
update: nutrition weekly organization filter
> update: nutrition weekly organization filter

- app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js
https://github.com/pfitzpaddy/ngm-reportDesk/issues/83
> update: no sum households in monthly form

- app/index.html
- app/views/modals/contact.html
Menu Organization path was to #/team changed back #/cluster/organization
+ in Contact RH  link to Youtube videos
#todo embed youtube videos
> update: organization menu path & youtube link in contacts

- app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js
- app/scripts/modules/cluster/reports/services/ngmClusterBeneficiaries.js
- app/scripts/modules/cluster/reports/services/ngmClusterHelper.js
- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
Reverts pfitzpaddy/ngm-reportHub#93
> Revert "cluster: add-distribution-date"

- app/index.html
- app/scripts/app/app.js
- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
- app/scripts/modules/cluster/views/forms/report/location/locations.html
- app/scripts/modules/country/afghanistan/drought/app.js
- app/scripts/modules/country/afghanistan/drought/dashboards/dashboard.drought.admin.js
- app/scripts/modules/country/afghanistan/drought/main/drought.main.js
- app/scripts/modules/country/afghanistan/drought/services/ngmDroughtHelper.js
- app/scripts/modules/country/afghanistan/drought/views/drought.admin.list.html
- app/scripts/modules/country/afghanistan/drought/views/drought.heatmap.html
- app/scripts/modules/country/afghanistan/drought/views/drought.main.html
- app/scripts/widgets/ngm-calHeatmap/calHeatmap.js
- app/scripts/widgets/ngm-calHeatmap/view.html
- app/scripts/widgets/ngm-html/template/drought.dashboard.html
add-drought-dashboard
#2
add-drought-dashboard
add-drought-dashboard
add-drought-dashboard
add-drought-dashboard
add-drought-dashboard
add-drought-dashboard
change month to start from 1 not 0
add-drought-dashboard
add-drought-dashboard
add-drought-dashboard
add -drought-dashboard
add-brought-dashboard
add-drought-dashboard
add and fixing  little detail
add-drought-dashboard
add current button, edit link 
add-drought-dashboard
setting button
add-drought-dashboard
add-drought-dashboard
add-drought-dashboard
add-drought-dashboard
add-drought-dashboard
add reporting organizations card 
add-drought-dashboard
add icon on reporting organization card
> feature-drought-dashboard

- app/scripts/modules/cluster/dashboards/dashboard.cluster.js
Add Active Location in 5W Dashboard
> add-active-location

- app/scripts/modules/country/afghanistan/drought/dashboards/dashboard.drought.admin.js
- app/scripts/widgets/ngm-html/template/drought.dashboard.html
Add Button  Previous Month in Drought Dashboard
> add- previous-button

- app/scripts/modules/country/afghanistan/nutrition/dashboards/dashboard.nutrition.weekly.js
- app/scripts/widgets/ngm-calHeatmap/calHeatmap.js
wait for the element exists on dom, continue the flow
and fix date filter path for nutrition dash
> fix: calheat initialization when element doesnt exist

- app/scripts/modules/cluster/dashboards/dashboard.cluster.js
- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
- app/scripts/widgets/ngm-highchart/highchart.js
add-active-location
add-pie-chart
add- pie-chart
add eldery pie chart
add-pie-chart
add-pie-chart
Add pie-chart for children,adult and elderly
> Add-pie-chart-for-dashboard

- app/scripts/widgets/ngm-calHeatmap/calHeatmap.js
looks like forEach breaks in phantomjs
> fix: phantomjs calheat change forEach to for loop

- app/scripts/modules/cluster/reports/forms/cluster.organization.form.stock.js
- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
- app/scripts/modules/cluster/views/forms/stock/stocks.html
move to ngmCLusterlist from cluster.organization.form.stock.js
show field based on report cluster not user
> update: stock-tergeted groups

- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
2 beneficiaries for health Chronic Illness and plain IDPs
> update: AF health beneficiary types

- app/scripts/widgets/ngm-table/templates/cluster/admin.progress.beneficiaries.html
add progress bar beside of percentage number
> update: add progress bar 

- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
- app/scripts/modules/cluster/views/forms/stock/stocks.html
Change name and for all cluster
> fix: stock targeted groups

- app/scripts/modules/cluster/dashboards/dashboard.admin.js
hide region and country filter when role user superadmin and user org is usaid
> fix: hide region and country filter

- app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js
add toast to inform user to save
> update: copy previous monthly report

- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
only AFG and USD units also for other clusters, cash activities
> update: cash reporting

- app/scripts/app/controllers/admin/controller.authentication.js
- app/scripts/modules/cluster/app.js
- app/scripts/modules/cluster/dashboards/dashboard.admin.js
- app/scripts/modules/cluster/dashboards/dashboard.cluster.js
- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
Country "Colombia" added to reportHub: in Authentication (Register) the 'AMER' region (America) and the country Colombia were added to countries list. Now users can access from Colombia to the Administration and 5wDashboard panels. In the filter menu of the 5wDashboard panel, the AMER region and the country Colombia were added. In the creation of projects, in the list of currencies, 'COP', of 'Colombian peso' was added.
> Feature colombia

- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
> update cluster: af fsac 2019

- app/scripts/modules/cluster/reports/controllers/cluster.project.documents.js
- app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js
- app/scripts/modules/cluster/views/forms/report/form.html
- app/scripts/modules/cluster/views/forms/report/report-upload.html
- app/scripts/widgets/ngm-list/template/list_upload.html
upload for monthly report document for now just for AF
> add: upload-monthlyreport

- app/scripts/modules/cluster/dashboards/dashboard.admin.js
- app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js
- app/scripts/widgets/ngm-list/template/admin.list.upload.html
> admin dashboard: add list of uploaded document

- app/scripts/modules/cluster/reports/controllers/cluster.project.report.js
Add zipped report docs in downloads.
> feat: zipped report docs

- app/scripts/modules/cluster/dashboards/dashboard.admin.js
- app/scripts/modules/cluster/views/cluster.project.summary.html
- app/scripts/modules/cluster/views/forms/details/form.html
- app/scripts/widgets/ngm-list/template/admin.list.upload.html
- set upload document just for AF right now
- remove card project document
> minor-change: set upload document feature just for AF 

- app/scripts/app/translate/locale-en.json
- app/scripts/app/translate/locale-es.json
- app/scripts/modules/cluster/dashboards/dashboard.admin.js
- app/scripts/modules/cluster/dashboards/dashboard.cluster.js
- app/scripts/modules/cluster/reports/services/ngmClusterBeneficiaries.js
- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
- app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html
> Feature col beneficiaries

- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
beneficiaries categories in monthly progress
> beneficiaries categories in monthly progress

- app/index.html
- app/scripts/app/app.js
- app/scripts/app/services/ngmAuthentication.js
- app/styles/ngm-menu.css
update hamburger menu to X when clicked
link demo
http://recordit.co/4kBwuzeOYO
> minor change: hamburger menu

- app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js
- app/scripts/modules/cluster/views/forms/report/location/locations.html
After OrderBy $locationIndex is of ordered array, later pointing to incorrect beneficiaries.
> bugfix(report): sort locations on controller to fix $locationIndex

- app/index.html
- app/promo/index.html
- app/promo/js/init.js
- app/scripts/app/app.js
- app/scripts/app/translate/locale-en.json
- app/scripts/app/translate/locale-es.json
- app/scripts/modules/cluster/reports/controllers/cluster.project.documents.js
- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
- app/scripts/modules/cluster/reports/services/ngmClusterHelper.js
- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
- app/scripts/modules/cluster/views/cluster.project.summary.html
- app/scripts/modules/cluster/views/forms/details/details.html
- app/scripts/modules/cluster/views/forms/report/report-upload.html
- app/scripts/widgets/ngm-list/template/admin.list.upload.html
- app/scripts/widgets/ngm-list/template/list_upload.html
- app/styles/main.css
- app/styles/ngm-form.css
- bower.json
Donors Colombia multiple select with md-contacts-chips.
Changes in bower.json:
angular-Material version: "angular-material": "^1.1.18".
"materialize": "0.97.7" ... deleted  ~0.97.7
> Donors Colombia multiple select, translate fixes

- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
> update(lists): add mpc drought beneficiary types

- app/scripts/app/translate/locale-en.json
- app/scripts/app/translate/locale-es.json
- app/scripts/modules/cluster/dashboards/dashboard.admin.js
> fix(admin): change stocks total projects to warehouses

- app/index.html
- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
- app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js
- app/scripts/modules/cluster/reports/services/ngmClusterDocument.js
- app/scripts/modules/cluster/views/forms/details/project-upload.html
- app/scripts/modules/cluster/views/forms/report/report-upload.html
-add ngmCLusterDocument file
-change list view for report upload not use table anymore (report-upload.html)
-minor change and report-upload.html and project-upload.html
> Refactor upload document to service 

- app/index.html
- app/promo/index.html
- app/promo/js/init.js
- app/scripts/app/app.js
- app/scripts/app/controllers/admin/controller.login.js
- app/scripts/app/controllers/admin/controller.register.js
- app/scripts/app/translate/locale-en.json
- app/scripts/app/translate/locale-es.json
- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
Landing page in spanish, functionality to show ReportHub or 4wPlus (for domain: '4wplus.org')
> Landing page in spanish, functionality to show ReportHub or 4wPlus if the domain is '4wplus.org')

- app/promo/js/init.js
- app/scripts/app/app.js
- app/scripts/app/controllers/admin/controller.login.js
- app/scripts/app/controllers/admin/controller.register.js
- app/scripts/app/translate/locale-en.json
- app/scripts/app/translate/locale-es.json
- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
- app/scripts/modules/cluster/views/forms/details/details.html
- app/scripts/modules/cluster/views/forms/details/target-locations/locations.html
- app/styles/main.css
- app/views/modals/contact.html
implementing_partners select in ProjectPlan search for organization_name. Fixes in contact html. Translate in locations.
> implementing_partners select Fixes. Contact and translate.

- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
In cluster.project.form.details.js:
For the implementation Select Donors, in function afterSelectItem(), functionality to set Donors Selected array to  each 'target_locations.project_donor' array.
> set Donors Selected array to  each 'target_locations.project_donor' array

- app/scripts/app/controllers/admin/controller.authentication.js
- app/scripts/app/views/authentication/register.html
- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
when register, cluster show based on the country that user pick/select
> register: cluster based on country

- app/scripts/app/controllers/admin/controller.authentication.js
- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
In controller.authentication.js  Register() function added conditional instruction if user.admin0pcode == ‘COL, the variable country = ‘col’ or  country = ‘other’. With this value, search the ‘cluster’ list for ‘col’ or for ‘other’. Cluster list ‘col’ have the cluster list for Colombia, and the list ‘other’ have the cluster list for the others countries.
> Fixes Authentication Controller Register function  with Clusters for Colombia

- app/scripts/modules/cluster/dashboards/dashboard.admin.js
- app/scripts/modules/cluster/dashboards/dashboard.cluster.js
- app/scripts/modules/cluster/reports/controllers/cluster.project.details.js
- app/scripts/modules/cluster/reports/controllers/cluster.project.financials.js
- app/scripts/modules/cluster/reports/controllers/cluster.project.report.js
- app/scripts/modules/cluster/reports/controllers/cluster.project.reports.list.js
https://github.com/pfitzpaddy/ngm-reportDesk/issues/141
> feature (update):restrict downloads to user access levels

- app/scripts/app/controllers/admin/controller.authentication.js
- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
I made this change in Register() function, 
there was a bug in the registry of the 4wplus version.
> Fixes of bug in Register function in Authentication Controller

- app/scripts/widgets/ngm-table/templates/cluster/admin.progress.beneficiaries.html
- app/scripts/widgets/ngm-table/templates/cluster/admin.project.list.html
show clusters for cluster user, if applying https://github.com/pfitzpaddy/ngm-reportEngine/pull/103 to show other cluster reports/projects with this cluster defined activities
> update(admin): show cluster for cluster user

- app/promo/index.html
- app/promo/js/init.js
show landing page in Spanish if domain is https://4wplus.org/.
And 5w Dashboard link to: /desk/#/cluster/5w/amer/col. To show only data of Colombia
> fixes in landing page promo/index.html for 4wplus Colombia

- app/index.html
- app/promo/index.html
- app/promo/js/init.js
- app/scripts/app/app.js
- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
fixes in landing page and cluster/sectors list
>  fixes in landing page and cluster/sectors list

- app/scripts/app/controllers/admin/controller.authentication.js
- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
cvwg (Multi-Purpose Cash: Dinero Multi Propositio)  cluster added to Colombia Clusters list
> COL : cvwg (Multi-Purpose Cash: Dinero Multi Propositio)  cluster added to Colombia Clusters List

- app/scripts/app/controllers/admin/controller.authentication.js
- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
Added msd - Site Management and Site development Cluster to Colombia …Clusters List
> Clusters Colombia List

- app/scripts/modules/cluster/views/forms/financials/financials-COL.html
fixes in financial form Colombia
> fixes in financial report for Colombia

- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
Projects Classifications Colombia: 
Acuerdos de Paz
UNDAF - Desarrollo y Paz
DAC - OECD Development Assistance Committee
ODS - Objetivos de Desarrollo Sostenible
> updated projects classifications list for Colombia

- app/scripts/app/controllers/admin/controller.authentication.js
- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
Change Albergues Cluster name for Alojamientos/Asentamientos in ClusterLists and Authentication.
> Fixes Clusters List Colombia

- app/scripts/modules/cluster/reports/controllers/cluster.project.projects.js
- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
Country filter to user COUNTRY rol and new Colombia cluster
> Country filter to user COUNTRY rol and new Colombia cluster

- app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js
- app/scripts/modules/cluster/reports/services/ngmClusterBeneficiaries.js
- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
- app/scripts/modules/cluster/views/forms/report/location/locations.html
proposal
- add gradually location on scroll down while all not rendered incrementLocationLimitByOne
- set id on beneficiary and location and use updateSelectById on updates
- set also $beneficiaryIndex and $locationIndex on attributes to be able to update index value ( if modifying arrays )
note: tested on af
todo: on empty locations increment more, test for bugs
> update(mform): update select by id, add location by one on scroll down

- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
quick fix: put fatp condition on default activity row
> fix(mform): dont show not fatp rows

- app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html
minimal fix for title target beneficiaries if activity_detail_name exist
> fix: title target beneficiaries

- app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js
Small update: check on init if last location beneficiaries are complete inside check if the last location
> update: checks if beneficiaries exist

- app/scripts/modules/country/afghanistan/nutrition/assessments/nutrition.koboform.js
> bugfix(nutrition): amend filter typo

- app/scripts/app/services/ngmHelper.js
- app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js
- app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html
- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
- app/scripts/modules/cluster/views/forms/report/location/locations.html
1. When report is submitted or when project is complete, Demo maximize and minimize
2. Updated Card Title
monthly beneficiaries
target beneficiairies
> (re pull-request) feature: add minimize/maximize button and search for beneficiaries 

- app/scripts/app/directives/materialize.select.js
- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
- app/scripts/modules/cluster/reports/services/ngmClusterBeneficiaries.js
- app/scripts/modules/cluster/reports/services/ngmClusterLocations.js
- app/scripts/modules/cluster/views/forms/details/details.html
- app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html
- removing updateSelect from target beneficiaries
- removing updateSelect from project details
- set materialize-select watch on activity_type selects to track changes in option values
- removing updateSelect from add location for monthly
> update(project): remove updateSelect

- app/scripts/modules/cluster/dashboards/dashboard.admin.js
- app/scripts/modules/cluster/reports/controllers/cluster.project.projects.js
- app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js
- app/scripts/widgets/ngm-list/template/admin.list.upload.html
1. https://github.com/pfitzpaddy/ngm-reportDesk/issues/220
app/scripts/modules/cluster/dashboard/dashboards/dashboard.admin.js line : 451 
2. https://github.com/pfitzpaddy/ngm-reportDesk/issues/228
app/scripts/ngm-list/template/admin.list.upload.htm line : 6
3.https://github.com/pfitzpaddy/ngm-reportDesk/issues/230
app/scripts/modules/cluster/reports/controllers/ cluster.project.project.js line 93
4. https://github.com/pfitzpaddy/ngm-reportDesk/issues/232
app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js line 885
> fix:  add 'all' in sector menu, admin modal, project list title, not display copy last month button in project complete

- app/scripts/app/translate/locale-en.json
- app/scripts/app/translate/locale-es.json
- app/scripts/modules/cluster/reports/forms/cluster.project.form.financials.js
- app/scripts/modules/cluster/reports/services/COL/ngmClusterHelperCol.js
- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
- app/scripts/modules/cluster/views/cluster.home.page.html
- app/scripts/modules/cluster/views/forms/details/target-locations/locations.html
- app/scripts/modules/cluster/views/forms/financials/financials-COL.html
Fixes and implementations in COL Financial Report (Departamentos and Municipios). 
In TargetLocations, columns names changed for COL and changed option values in some lists. 
New words in translate files.
> COL Financial Report, TargetLocations columns options list.

- app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html
- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
> update(forms): show units for mpc cash, package, transfers

- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
- app/scripts/modules/cluster/reports/services/ngmClusterLocations.js
- app/scripts/modules/cluster/views/forms/details/target-locations/locations.html
order by createdAt
fixing locations jumps on edit save
call $cancel if target location id, fixing slicing glitch
> fix(targetlocations): keep order on save & $cancel if id

- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
https://github.com/pfitzpaddy/ngm-reportDesk/issues/241
> fix( project plan) : SO glitch

- app/scripts/modules/cluster/reports/controllers/cluster.project.summary.js
- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
- app/scripts/modules/cluster/views/cluster.project.summary.html
- app/scripts/modules/cluster/views/forms/details/form.html
Hide when country AF(except organization iMMAP) and remove project_startdate  when set project status to 'plan'
> update (project): hide button for project Implementation for AF and remove start_date

- app/scripts/modules/cluster/views/cluster.project.summary.html
- app/scripts/modules/cluster/views/forms/details/form.html
- app/scripts/modules/cluster/views/forms/financials/financials-COL.html
Hidden buttons 'Mark Project as Plan', etc... in Project Summary for COL.
Changed columns title in COL FinancialReport, 'Departamento', 'Municipio'
> Hidden buttons in project summary for Colombia. Columns title in COL FinancialReport

- app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html
- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
On changes of parent selection, update children options
> fix: watch changes on dependent selections

- app/scripts/app/translate/locale-en.json
- app/scripts/app/translate/locale-es.json
- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
- app/scripts/modules/cluster/reports/services/COL/ngmClusterHelperCol.js
- app/scripts/modules/cluster/views/forms/details/details.html
- app/scripts/modules/cluster/views/forms/details/project-classifications/classifications.html
- app/scripts/widgets/ngm-html/template/COL/projectdonor.html
- app/scripts/widgets/ngm-html/template/COL/responsecomponents.html
COL functions in cluster.project.form.details.js changed to ngmClusterHelperCol.js and COL sections in details.html changed to widgets/ngm-html/template/COL/ folder.
And fixes in COL response component and Col Project Classifications
> COL functions changed to ngmClusterHelperCol.js and sections in details.html changed to widgets/ngm-html/template/COL

- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
could be put onto activities config csv with organization column if activity specifically for organization to filter on ui later
> update(emergency fatp): remove hardcode on ui

- app/scripts/app/translate/locale-en.json
- app/scripts/app/translate/locale-es.json
- app/scripts/modules/cluster/reports/controllers/cluster.project.reports.group.js
- app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js
- app/scripts/modules/cluster/reports/services/ngmClusterBeneficiaries.js
- app/scripts/modules/cluster/views/forms/report/form.html
- app/scripts/modules/cluster/views/forms/report/report.group.html
example interface for removing reports out of project date range, on out of range remove button will be shown, ( for clearly knowing what user does, its shown only on todo reports inside report itself )
two commits one for regular reports, another for groups if needed ( the same but on main groups page )
> Feature delete out of project date range report

- app/scripts/modules/cluster/views/forms/details/target-locations/CB/locations.html
that cb uses different locations html without fixes for jumping on save and cancel edit blocking bug
if needed
note: also empty spaces updates due to edit config included
> update(cb target locations): add ordering and blocked cancel edit fix

- app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html
- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
activities csv updated ( including Colombia options @sebasnavarreteImmap please check )
on activities import + 
```
db.getCollection('activities').find({}).forEach(function (d) { if( d.mpc_mechanism_type_id.length ) { d.mpc_mechanism_type_id = JSON.parse(d.mpc_mechanism_type_id); db.getCollection('activities').save(d); } });
```
also on no mechanism options, it will be dissabled
+ file empty spaces removals
> update(cash): get mechanism options from activities config

- app/scripts/app/controllers/admin/controller.authentication.js
- app/scripts/modules/cluster/reports/controllers/cluster.project.projects.js
Profile page updated because : the organization is empty array show because in panel.organization_list not have admin0pcode: 'ALL"' just admin0pcode:'' or 'COL'
Project list : need to add '/'
> fix(minor in profile and project list)

- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
Added Coordinación/Información Colombia Cluster to Colombia clusters list
> Coordinación/Información Colombia Cluster

- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
> hotfix: monthly report form add mpc  delivery field for activitis ( food assistance in-kind food)

- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
update: change from {{index}} to{{ $locationIndex }}-{{$beneficiaryIndex}}
> update(minor): label monthly report form

- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
COL Donors list sorted alphabetically
> COL donors list updated

- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
fixes COL Organizations in implementing partners list
> Project Plan COL organizations in implementing partners 

- app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html
- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
revert: watch selections in beneficiaries
> revert: watch selections in beneficiaries

- app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html
- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
As transfer already on units line, assuming mpc delivery implies units, reducing combinatorics,
note: space removal updates on beneficiaries.html, ignore if not needed
> refactor(beneficiaries): remove transfer selection from mpc line

- app/scripts/modules/cluster/reports/services/CB/ngmCbLocations.js
- app/scripts/modules/cluster/views/forms/details/target-locations/CB/locations.html
- removing global update select
- removing filterLocations from setLocationType as already in setLocationsInputs
- setting watch on admin2,3 (note: to reinitialize when their value is not changed, admin1 inited by setting default inputs, site_id by setSite)
- correcting user lists reference
- sort targetlocations on setLocationsForm to match filter arrays to view sort $index
> CB location proposed updates

- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
if target-location or target-beneficiaries more than 30
Maximize the first one, and minimize the rest
> update( project details) : minimize targets on page init

- app/scripts/widgets/ngm-highchart/template/promo.html
> update(dashboard cluster): change format subLabel in the center  of highchart (donut/chart)

- app/index.html
- app/styles/main.css
> feature: add loading bar when initial load

- app/scripts/modules/cluster/dashboards/dashboard.4wprojectplan.js
- app/scripts/modules/cluster/dashboards/dashboard.dashboard4wplus.js
added donor filter to downloads (projects, beneficiaries reports, financial reports) in projectplan and 4wplus activities dashboards
> added donor filter to downloads

- app/scripts/modules/cluster/reports/services/ngmClusterBeneficiaries.js
- app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html
- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
Commits for various MPC related fixes: 
1 fix: clear name attribute if id one is null on update name
1 will add into updateName fn condition:
if ( beneficiary[ key ] === null ){
beneficiary[ name ] = null
}
2 update: use activities.csv list for mechanism update name param
3 fix: correct mpc delivery update name list param
4 fix: correct transfer update name param
5 fix: clear cash attribute values on activity change
> MPC related fixes

- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
Unblock save project button if save results in any server error
> fix(project): unblock save on response error

- app/scripts/modules/cluster/reports/services/NG/ngmClusterHelperNgWash.js
- app/scripts/modules/cluster/views/forms/report/beneficiaries/NG/wash/hygiene/promotion.html
- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
@dondippino please take a look
fix(ng): clear associations on activity change
fix(ng): hide add button for promotion activity with no template
> Fix ng association activity change

- app/index.html
- app/scripts/app/views/authentication/team.html
- app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html
- app/scripts/modules/cluster/views/forms/report/location/locations.html
- app/scripts/widgets/ngm-highchart/template/promo.html
- app/scripts/widgets/ngm-list/template/default.html
- app/scripts/widgets/ngm-list/template/hide_list.html
- app/scripts/widgets/ngm-list/template/report.html
- app/scripts/widgets/ngm-list/template/report_somalia.html
- app/scripts/widgets/ngm-list/template/stock.html
- app/styles/ngm-form.css
1. fix error label
2. search icon
3. highchart title
> fix-minor for materialize 1.x

- app/scripts/app/views/authentication/team.html
- app/scripts/modules/immap/controllers/immap.products.js
- app/styles/main.css
align download and title
fix style immap product page, team page
> minor update style- materialize 1.x

- app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js
fix the issue when activity cluster is overwritten with report's cluster
> fix(copy report): don't use report's cluster

- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
- app/scripts/modules/cluster/reports/services/ngmClusterLocations.js
- app/scripts/modules/cluster/views/forms/details/target-locations/locations-reform.html
test cases:
1. Add new location
2. Remove location
3. Edit Location ( change province, change site name, etc )
4. Activities check
5. opening new (add new target location on a new project)
6. checking locations in reports, correct location info saved
> Change form Target location

- app/scripts/modules/cluster/reports/services/activity-details/ngmClusterDetails.js
- app/scripts/modules/cluster/views/forms/report/beneficiaries/activity-details/activity-details.html
- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
Proposal: 
1 using materialize-select watch
2 initDetails run only on current beneficiaries
3 selects would update on each select change
**Please check and test**
> fix(beneficiaries): update details init processing

- app/scripts/modules/cluster/dashboards/dashboard.4wprojectplan.js
- app/scripts/modules/cluster/dashboards/dashboard.dashboard4wplus.js
fixes to show data in graphics
> fixes january projectplan and activities dashboards

- app/scripts/app/controllers/admin/controller.team.js
- app/scripts/app/views/authentication/team.html
- app/scripts/modules/cluster/reports/forms/cluster.organization.form.stocks.list.js
and also 
fix bug for modal in stock location
> add-tag for org admin in team page and fix bug

- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
update(AF wash): change population group name
> update(AF wash): change population group name

- app/scripts/modules/cluster/dashboards/dashboard.cluster.js
Addition of other roles to the custom download feature on ReportHub
> Fixing roles and privileges for custom downloads

- app/scripts/app/views/authentication/login.html
> bugfix(minor): the login form is stretched out of page on navigation

- app/scripts/modules/cluster/reports/services/ngmClusterDocument.js
- app/scripts/modules/cluster/views/forms/details/project-upload.html
- app/scripts/modules/cluster/views/forms/report/report-upload.html
fix(upload): add close modal classes
> fix(upload): add close modal classes

- app/scripts/app/translate/locale-en.json
- app/scripts/app/translate/locale-es.json
- app/scripts/app/translate/locale-prs.json
- app/scripts/modules/cluster/reports/forms/cluster.project.form.financials.js
- app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html
- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
change label amount to transfer value if mpc delivery is exist
fix bug: financial multi-year when start date and end date the same
> minor update: change label name and fix bug multi year financial form

- app/scripts/modules/cluster/reports/services/NG/ngmClusterHelperNgWashValidation.js
- app/scripts/widgets/ngm-dropzone/dropzone.js
there were some hanging Materialize.toast => M.toast in validate ng and doprocess dropzone
note: not tested
> fix(toasts): correct to M.toast reference

- app/scripts/app/views/authentication/team.html
Put tag on top of country name
From
to
> minor-update(team page): change position tag 

- app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html
- app/scripts/modules/cluster/views/forms/details/target-locations/CB/locations.html
- app/scripts/modules/cluster/views/forms/details/target-locations/locations-reform.html
- app/scripts/modules/cluster/views/forms/financials/financial-reform.html
- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
- app/scripts/widgets/ngm-dropzone/template/default.html
- app/scripts/widgets/ngm-html/template/bgd/gfd/daily.report.forms.html
- app/styles/main.css
remove duplicate css and put it in main css
> minor-update:remove unused html and put same class css in main.css

- app/scripts/app/controllers/admin/controller.authentication.js
- app/scripts/app/views/authentication/team.html
1.add link to open user profile in a new page
2.  on delete or deactivate navigation to the previous team page path
> update : team page 

- app/scripts/modules/cluster/views/forms/details/target-locations/locations-reform.html
> bugfix: align button if type site type is missing on target location

- app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html
- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
used in AF, in addition to delivery, mechanism, package fieldset
> update(mpc): add delivery, package form fieldset

- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
to fix the issue when target beneficiaries array order not matching UI order for projects with target beneficiaries created before the current project save processing functionality
> fix(validation): set target beneficiaries order as ui

- app/scripts/app/controllers/admin/controller.authentication.js
- app/scripts/app/views/authentication/login.html
- app/scripts/app/views/authentication/register.html
- app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js
- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
- app/scripts/modules/cluster/views/forms/report/form.html
1. disable on form save button on save request to fix no id duplication issues
2. disable login button on login request
3. disable register button on register request
> fix(beneficiaries): disable save btn on save

- app/index.html
- app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js
- app/scripts/modules/cluster/reports/services/ngmClusterBeneficiaries.js
- app/scripts/modules/cluster/reports/services/ngmClusterValidation.js
- app/scripts/modules/cluster/views/forms/report/location/locations.html
- app/styles/ngm-form.css
Demo for import file xlsx or csv
Demo for import data by copy paste from excel
For now, this feature active just on AF
> update(monthly report): add feature import file (csv, xlsx, copy paste from excel) for monthly report 

- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
or/and to set project_details: [] to all records
> fix(project): check if no project details array

- app/scripts/modules/cluster/reports/services/ngmClusterBeneficiaries.js
- app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html
- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
> update : change atrribute 'specifics' to reponse

- app/scripts/modules/cluster/reports/forms/cluster.organization.form.stock.js
- app/scripts/modules/cluster/reports/services/ngmClusterBeneficiaries.js
- undefined stocks
- undefined details
> undefined length fixes

- app/scripts/app/translate/locale-en.json
- app/scripts/app/translate/locale-es.json
- app/scripts/app/translate/locale-prs.json
- app/scripts/modules/cluster/reports/controllers/cluster.project.report.js
- app/scripts/modules/cluster/reports/controllers/cluster.stock.js
- app/scripts/modules/cluster/reports/forms/cluster.organization.form.stock.js
- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
download a file without request by running a function that writes to buffer 
- stock lists
- population groups
uses ExcelJS
uses client download type, dependant on https://github.com/pfitzpaddy/ngm-dashboard-framework/pull/8
> Feat download stock list client

- app/index.html
- app/scripts/modules/cluster/reports/controllers/cluster.project.details.js
- app/scripts/modules/cluster/reports/controllers/cluster.project.report.js
- app/scripts/modules/cluster/reports/controllers/cluster.stock.js
- app/scripts/modules/cluster/reports/services/ngmClusterDownloads.js
adding ngmClusterDownloads which contains client processing logic
> refactor(download client): add downloads service

- app/scripts/modules/cluster/app.js
set AF 5w start year to current else default 2018
> update(5w af): set this reporting year start date

- app/scripts/modules/cluster/app.js
- app/scripts/modules/cluster/reports/controllers/cluster.project.details.js
- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
- app/scripts/modules/cluster/reports/services/ngmClusterBeneficiaries.js
- app/scripts/modules/cluster/reports/services/ngmClusterHelper.js
- app/scripts/modules/cluster/reports/services/ngmClusterLocations.js
- app/scripts/modules/cluster/reports/services/ngmClusterValidation.js
- app/scripts/modules/cluster/views/forms/details/details.html
- app/scripts/modules/cluster/views/forms/details/form.html
For now just for AF
Import file => make new  project based on  file excel that user upload
project  copy => make new project based on existing project
> update(project detail AF): Add import file for project and add project copy

- app/scripts/modules/cluster/reports/controllers/cluster.stock.js
- app/scripts/modules/cluster/reports/controllers/cluster.stocks.list.js
on warehouses param in getOrganization request will also get warehouses
> update(organization): add warehouses param on set

- app/scripts/app/translate/locale-en.json
- app/scripts/app/translate/locale-es.json
- app/scripts/app/translate/locale-prs.json
- app/scripts/modules/cluster/reports/controllers/cluster.stocks.list.js
- app/scripts/modules/cluster/reports/services/ngmClusterDownloads.js
> update(download): add stock warehouses list

- app/scripts/app/controllers/admin/controller.authentication.js
- app/scripts/app/views/authentication/register.html
Note:
ALL, COL should be updated to COL
ALL or AF,COL,CB,CD,ET,IQ,KE,NG,SO,SS,SY,UA,UR,YE can be used
> update(register): organizations filtered by country

- app/scripts/app/controllers/admin/controller.authentication.js
- app/scripts/modules/cluster/app.js
- app/scripts/modules/cluster/dashboards/dashboard.4wprojectplan.js
- app/scripts/modules/cluster/dashboards/dashboard.admin.js
- app/scripts/modules/cluster/dashboards/dashboard.cluster.js
- app/scripts/modules/cluster/dashboards/dashboard.dashboard4wplus.js
- app/scripts/modules/cluster/reports/controllers/cluster.project.projects.js
[gdrive/admin scripts/pg](https://drive.google.com/drive/folders/1zLPb9p0wxrLvDshWJTtzYjLhV05OBNPG?usp=sharing)
admin0pcode - PG
added admin1,2,3
Notes:  as per admin boundaries names contain Province, District, LLG
> update(admins): add WPRO and PG

- app/index.html
- app/scripts/app/app.js
- app/scripts/modules/cluster/app.js
- app/scripts/modules/cluster/lists/cluster.list.admin.js
- app/scripts/modules/cluster/lists/cluster.list.organizations.js
- app/scripts/modules/cluster/lists/form/list.org.form.js
- app/scripts/modules/cluster/lists/views/cluster.list.admin.html
- app/scripts/modules/cluster/lists/views/organization.list.html
-add new organization
-edit organization 
-delete organization
-enable/disable organization in a certain country
- search organization
> feature : Organization Lists

- app/scripts/modules/cluster/lists/form/list.org.form.js
- app/scripts/modules/cluster/views/lists/organization.list.html
Note:
Needs to Update for Organization
> update(org list): update org list flow (chekbox, uncheck, disable & enable organization on country)

- app/index.html
- app/scripts/app/app.js
- app/scripts/modules/cluster/app.js
- app/scripts/modules/cluster/reports/controllers/cluster.beneficiaries.stock.admin.js
- app/scripts/modules/cluster/reports/forms/cluster.upload.beneficiaries.stock.report.js
- app/scripts/modules/cluster/reports/services/ngmClusterImportFile.js
- app/scripts/modules/cluster/views/cluster.upload.beneficiaries.stock.report.html
For now only for AF
-Menu
-beneficiaries 
-stocks
> Feature : Beneficiaries and Stocks record Admin

- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
- add population groups
- fix conditions on site implementations
- correct site implementations spelling
> Update protection 2020 v2

- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
'General'   => 'Non-Disabled'
'Disabled' => 'Persons with Disabilities'
just for AF
> update(af beneficiary categories): use appropriate terms

- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
- app/scripts/modules/cluster/reports/services/ngmClusterBeneficiaries.js
- app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html
- app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
and bug fix 
- response checkbox
> bugfix(import): project details 

- app/scripts/modules/cluster/reports/forms/cluster.organization.form.stock.js
- app/scripts/modules/cluster/reports/services/ngmClusterValidation.js
- app/scripts/modules/cluster/views/cluster.upload.beneficiaries.stock.report.html
- app/scripts/modules/cluster/views/forms/stock/stocks-reform.html
> update(stock): update form 

- app/scripts/modules/cluster/reports/forms/cluster.organization.form.stock.js
- app/scripts/modules/cluster/views/forms/stock/stocks-reform.html
fixing stocks implementing partners and donors properties to be with an array value
> Fix stocks ip donors array

- app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
- app/scripts/modules/cluster/reports/services/ngmClusterLists.js
- set users on project date update
- get all organization users not just cluster
> Fix users list on project date update

- app/scripts/app/controllers/admin/controller.authentication.js
- app/scripts/app/controllers/admin/controller.profile.js
- app/scripts/app/views/authentication/profile.html
Right now just for AF
If the profile set to private it will look like this
> update(profile): add checkbox to set profile to private 

- app/scripts/modules/cluster/reports/services/ngmClusterValidation.js
> fix(beneficiaries validation): when id of element that does not exist is passed to scroll to 

- app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js
- app/scripts/modules/cluster/reports/services/ngmClusterLocations.js
- app/scripts/modules/cluster/reports/services/ngmClusterValidation.js
- app/scripts/modules/cluster/views/forms/report/location/add.location-reform.html
- app/scripts/modules/cluster/views/forms/report/location/locations.html
> update(monthly report): refactor add location on monthly report

- app/index.html
- app/scripts/modules/cluster/app.js
- app/scripts/modules/cluster/dashboards/dashboard.performance.js
- app/scripts/widgets/ngm-html/template/performance-btn.html
- app/scripts/widgets/ngm-html/template/performance.html
> add: new dashboard for performance
